from enum import StrEnum


class ErrorCode(StrEnum):
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
    GRADIO_START_FAILED = "GRADIO_START_FAILED"
    FASTAPI_UNAVAILABLE = "FASTAPI_UNAVAILABLE"
    LLM_PROVIDER_UNAVAILABLE = "LLM_PROVIDER_UNAVAILABLE"
    SCRIPT_VALIDATION_FAILED = "SCRIPT_VALIDATION_FAILED"
    FFMPEG_NOT_FOUND = "FFMPEG_NOT_FOUND"
    FFMPEG_CONCAT_FAILED = "FFMPEG_CONCAT_FAILED"
    WANGP_UNAVAILABLE = "WANGP_UNAVAILABLE"
    TTS_UNAVAILABLE = "TTS_UNAVAILABLE"
    PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
    INVALID_PROJECT_STATE = "INVALID_PROJECT_STATE"
    TEMPLATE_PROVIDER_FAILED = "TEMPLATE_PROVIDER_FAILED"
    FILE_SYSTEM_ERROR = "FILE_SYSTEM_ERROR"
    CONFIG_INVALID = "CONFIG_INVALID"
    BOOT_FAILED = "BOOT_FAILED"
